# Generated by Django 3.0.8 on 2020-07-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'poll', 'question')},
        ),
    ]
